### ISSUE TITLE
Choose hosting services

### ISSUE THREAD

**Issue by ghost** [xternprojects/fundfest-backend#3]

**Comment by bwencke** [comment]
Some considerations: There will be a budget for this, but obviously it would be best to keep the cost down. We need something scalable because it will go from nothing to TONS of requests almost in an instant once the event begins.

**Comment by ghost** [comment]
We can use Heroku as suggested in the cultural trails backend project

**Comment by bwencke** [comment]
Isn't this done? Please close issues that have been completed.
